apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  labels:
    app: robot-shop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mongodb.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongodb.storage }}
